### ISSUE TITLE
Anmeldeformular für Motorfurs

### ISSUE THREAD

**Issue by kidran** [sachsenfurs/sigma#101]
Für die Teilnahme am Motorfurs wird ein Anmeldeformular benötigt

Folgende Daten werden beötigt:

- Nick
- TG Handle
- Foto vom Auto
- Kennzeichen
- Freitext (Absatz)

Formular soll unabhängig von einem Event verfügbar sein, weil wir die Anmeldung gerne ca. 4 Wochen vor der Con machen wollen.

**Comment by R1N4x** [comment]
Ein Formular sollte mehreren Events zuweisbar sein. 

Motorfurs hat dieses Jahr zwei Events. Bei beiden Events soll man auf ein und das selbe Formular zur Anmeldung kommen. 

Beschreibungstext für "Textbereich" im Formular wäre schön. (So das man dort beschreiben kann was der Anmelder in das Feld schreiben soll/kann)

**Comment by R1N4x** [comment]
Wiedereröffnet weil: 

Beschreibungstext für "Textbereich" im Formular wäre schön. (So das man dort beschreiben kann was der Anmelder in das Feld schreiben soll/kann)

Wäre cool wenn jedes Eingabefeld die Option hätte dort einen "Beschreibungstext" zu definieren um dem Teilnehmer ein wenig zu erklären was in das Feld rein soll.
